CREATE DATABASE IF NOT EXISTS `HOLTERDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `HOLTERDB`;

CREATE TABLE PARAMETROS(
	ID_PARAMETRO INT NOT NULL AUTO_INCREMENT,
	FRECARDIACAMIN INT UNSIGNED NOT NULL,
	FRECARDIACAMAX INT UNSIGNED NOT NULL,
	CANTIDADMEDICIONES INT UNSIGNED NOT NULL,
	FECHA_CREACION DATETIME NULL,
	CONSTRAINT PK_PARAMETROS_ID_PARAMETRO PRIMARY KEY (ID_PARAMETRO)
) COMMENT='Historial de datos simulados de la frecuencia mínima y máxima Holter del paciente';

CREATE TABLE USUARIOS(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASS VARCHAR(40) NOT NULL,
	TIPO_USUARIO SET('ADMIN','USER') DEFAULT 'USER' NOT NULL,
	CREACION_USUARIO DATETIME NOT NULL,
	MODIFICACION_USUARIO DATETIME NOT NULL,
	CONSTRAINT PK_USUARIOS_ID_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (EMAIL)
) COMMENT='Contiene los usuarios que se loguean al sistema';

CREATE TABLE TIPODOCUM (
	ID_TIPODOCUM INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(250) NULL,
	CONSTRAINT PK_TIPODOCUM_ID PRIMARY KEY (ID_TIPODOCUM),
	CONSTRAINT UK_TIPODOCUM_NOMBRE UNIQUE (NOMBRE),
	CONSTRAINT UK_TIPODOCUM_SIGLA UNIQUE (SIGLA)
) COMMENT='Contiene los diferentes tipos de documentos por personas';

CREATE TABLE PACIENTE(
	ID_PACIENTE INT NOT NULL AUTO_INCREMENT,
	TIPODOCUM_ID_TIPODOCUM INT NOT NULL,
	DOCUMENTO INT NOT NULL,
	NOMBRES VARCHAR(100) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	FECHA_NACIMIENTO DATETIME NOT NULL,
	GENERO SET('', 'M','F') DEFAULT '' NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	CONSTRAINT PK_PACIENTE_ID_PACIENTE PRIMARY KEY (ID_PACIENTE),
	CONSTRAINT UK_PACIENTE_TIPODOCUM_DOCUMENTO UNIQUE (TIPODOCUM_ID_TIPODOCUM, DOCUMENTO),
	CONSTRAINT FK_PACIENTE_TIPODOCUM_ID FOREIGN KEY(TIPODOCUM_ID_TIPODOCUM) REFERENCES TIPODOCUM(ID_TIPODOCUM)
) COMMENT='Contiene los diferentes tipos de documentos usado entre empresas y personas';

CREATE TABLE HISTORIAPACIENTE(
	PACIENTE_ID_USUARIO INT NOT NULL,
	ANOMALIA VARCHAR(1000) NOT NULL,7
	CREACION_USUARIO DATETIME NOT NULL,
	MODIFICACION_USUARIO DATETIME NOT NULL,
	CONSTRAINT FK_HISTORIAPACIENTE_PACIENTE_ID_USUARIO FOREIGN KEY(PACIENTE_ID_USUARIO) REFERENCES PACIENTE(ID_PACIENTE)
) COMMENT='Historia clínica del paciente';

CREATE TABLE MEDICIONPACIENTE(
	ID_MEDICIONPACIENTE BIGINT NOT NULL AUTO_INCREMENT,
	PACIENTE_ID_USUARIO INT NOT NULL,
	PARAMETROS_ID_PARAMETRO INT NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	FRECUENCIA_MIN INT NOT NULL,
	FRECUENCIA_MAX INT NOT NULL,
	TOTAL_PUNTOS  INT NOT NULL,
	FECHA_INICIO DATETIME NOT NULL,
	FECHA_FIN DATETIME NOT NULL,
	CONSTRAINT PK_PACIENTE_ID_MEDICIONPACIENTE PRIMARY KEY (ID_MEDICIONPACIENTE),
	CONSTRAINT UK_PACIENTE_MEDICIONPACIENTE UNIQUE (ID_MEDICIONPACIENTE),
	CONSTRAINT FK_MEDICIONPACIENTE_PACIENTE_ID_USUARIO FOREIGN KEY(PACIENTE_ID_USUARIO) REFERENCES PACIENTE(ID_PACIENTE)
	CONSTRAINT FK_MEDICIONPACIENTE_PACIENTE_ID_USUARIO FOREIGN KEY(PARAMETROS_ID_PARAMETRO) REFERENCES PARAMETROS(ID_PARAMETRO)
) COMMENT='Historial de mediciones de Holter del paciente';




